<<<<<<< HEAD
import { supabase } from "../supabase/client";
=======
// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();
>>>>>>> 9a097937a83c99b045df78274b2e655078e2daaf

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
<<<<<<< HEAD
      if (provider !== "google") {
        return { error: new Error(`OAuth provider '${provider}' is not supported`) };
      }
      const { error } = await supabase.auth.signInWithOAuth({
        provider: "google",
        options: {
          redirectTo: opts?.redirect_uri ?? `${window.location.origin}/dashboard`,
          queryParams: opts?.extraParams,
        },
      });
      if (error) return { error };
      return { redirected: true };
=======
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
>>>>>>> 9a097937a83c99b045df78274b2e655078e2daaf
    },
  },
};
